
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: kubernetes.io/basic-auth
stringData:
  password: D3@dK3nn3dy$
  username: app_root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anarchyforsale-admin
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": "anarchyforsale-admin"
      app: admin-api
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "anarchyforsale-admin"
        app: admin-api
    spec:
      containers:
      - name: web
        image: killyosaur/ishara.admin.api:0.0.7
        env:
        - name: DB_PORT
          value: "8529"
        - name: DB_HOST
          value: "https://anarchy-db.default.svc"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: mysecret
        - name: DB_PWRD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysecret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /etc/ssl/certs/anarchy-db.pem
            name: ca-cert
            subPath: ca.crt
            readOnly: false
      volumes:
      - name: tls-cert
        secret:
          secretName: anarchy-db-single-kxojn75h-tls-keyfile
      - name: ca-cert
        secret:
          secretName: anarchy-db-ca

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort
  selector:
    app: admin-api
  ports:
  - port: 5000
    targetPort: 50000
    nodePort: 30050
