apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "anarchy-db-cluster"
spec:
  bootstrap:
    passwordSecretNames:
      root: arango-root
  mode: Cluster
  image: "arangodb/arangodb:latest"
  type: None
  agents:
    resources:
      requests:
        storage: 5Gi
    storageClassName: do-block-storage
  dbservers:
    resources:
      requests:
        storage: 10Gi
    storageClassName: do-block-storage