apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
  spec:
    containers:
    - name: myapp
      image: arangodb/arangodb:latest
      env:
        - name: ARANGO_ROOT_PASSWORD
          value: t3mpP@ssw0rd
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arango-root
              key: password
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              name: application-root
              key: username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application-root
              key: password
      ports:
        - containerPort: 9376
