export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    WARNING: 'ALERT_WARNING',
    INFORMATION: 'ALERT_INFORMATION',
    CLEAR: 'ALERT_CLEAR',
    CLEARALL: 'ALERT_CLEARALL',
    REMOVE: 'ALERT_REMOVE'
};
